version: '3.8'
services:
  api:
    image: learn-nesjs
    container_name: api
    env_file:
      - ./.env
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - .:/tmp/src/app:cached
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - .docker/data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
